import type { NextConfig } from 'next';
import legacyRedirects from './legacy-redirects.json';

const nextConfig: NextConfig = {
  // Old WordPress links end in a trailing slash. Without this, Next strips the
  // slash in its own redirect first, so an old link costs two hops before it
  // reaches the article. The generated rules below match both slash forms, so
  // one hop is enough.
  skipTrailingSlashRedirect: true,
  // Old WordPress URLs -> /article/<slug>. Generated by
  // scripts/generate-legacy-redirects.mjs; see that file for why.
  async redirects() {
    return legacyRedirects;
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'historyalivetoday.com',
      },
      {
        protocol: 'https',
        hostname: '*.public.blob.vercel-storage.com',
      },
    ],
  },
};

export default nextConfig;
