import type { NextConfig } from 'next';
import legacyRedirects from './legacy-redirects.json';

const nextConfig: NextConfig = {
  // Old WordPress URLs -> /article/<slug>. Generated by
  // scripts/generate-legacy-redirects.mjs; see that file for why.
  async redirects() {
    return legacyRedirects;
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'historyalivetoday.com',
      },
      {
        protocol: 'https',
        hostname: '*.public.blob.vercel-storage.com',
      },
    ],
  },
};

export default nextConfig;
